AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless Image Service (API Gateway + Lambda + S3 + DynamoDB)

Globals:
  Function:
    Runtime: python3.9
    Timeout: 20
    MemorySize: 256
    Tracing: Active
    Environment:
      Variables:
        IMAGES_TABLE: !Ref ImagesTable
        IMAGES_BUCKET: !Ref ImagesBucket
        PRESIGN_TTL_SECONDS: 900

Resources:
  ApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      StageName: prod
      Cors:
        AllowMethods: "'GET,POST,DELETE,OPTIONS'"
        AllowHeaders: "'*'"
        AllowOrigin: "'*'"

  CreateImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handlers.create_image
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTable
        - Statement:
            - Effect: Allow
              Action:
                - s3:PutObject
                - s3:GetObject
                - s3:DeleteObject
              Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
      Events:
        ApiPost:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /images
            Method: POST

  ListImagesFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handlers.list_images
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ImagesTable
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
      Events:
        ApiGetList:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /images
            Method: GET

  GetImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handlers.get_image
      Policies:
        - DynamoDBReadPolicy:
            TableName: !Ref ImagesTable
        - Statement:
            - Effect: Allow
              Action: s3:GetObject
              Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
      Events:
        ApiGetOne:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /images/{image_id}
            Method: GET

  DeleteImageFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.handlers.delete_image
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTable
        - Statement:
            - Effect: Allow
              Action: s3:DeleteObject
              Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
      Events:
        ApiDelete:
          Type: Api
          Properties:
            RestApiId: !Ref ApiGateway
            Path: /images/{image_id}
            Method: DELETE

  S3MarkAvailableFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: app.s3_event_handler.mark_available
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ImagesTable
        - Statement:
            - Effect: Allow
              Action:
                - s3:GetObject
              Resource: !Sub arn:aws:s3:::${ImagesBucket}/*
      Events:
        PutEvents:
          Type: S3
          Properties:
            Bucket: !Ref ImagesBucket
            Events: s3:ObjectCreated:*

  ImagesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: image_id
          AttributeType: S
        - AttributeName: user_id
          AttributeType: S
        - AttributeName: created_at
          AttributeType: S
      KeySchema:
        - AttributeName: image_id
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: GSI1
          KeySchema:
            - AttributeName: user_id
              KeyType: HASH
            - AttributeName: created_at
              KeyType: RANGE
          Projection:
            ProjectionType: ALL

  ImagesBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      CorsConfiguration:
        CorsRules:
          - AllowedHeaders: ["*"]
            AllowedMethods: ["GET", "PUT", "DELETE", "HEAD"]
            AllowedOrigins: ["*"]
            MaxAge: 3000

Outputs:
  ApiUrl:
    Description: API base URL
    Value: !Sub "https://${ApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod"
  BucketName:
    Description: S3 bucket name
    Value: !Ref ImagesBucket
  TableName:
    Description: DynamoDB table name
    Value: !Ref ImagesTable
